/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.salesvision.getLeadsData.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.salesvision.getLeadsData.model.RecordsEntryItem;
import java.util.ArrayList;
import java.util.List;
/**
 * RootResponse
 */

public class RootResponse {
  @JsonProperty("totalSize")
  private Integer totalSize = null;

  @JsonProperty("records")
  private List<RecordsEntryItem> records = new ArrayList<>();

  @JsonProperty("done")
  private Boolean done = null;

  public RootResponse totalSize(Integer totalSize) {
    this.totalSize = totalSize;
    return this;
  }

   /**
   * Get totalSize
   * @return totalSize
  **/
  public Integer getTotalSize() {
    return totalSize;
  }

  public void setTotalSize(Integer totalSize) {
    this.totalSize = totalSize;
  }

  public RootResponse records(List<RecordsEntryItem> records) {
    this.records = records;
    return this;
  }

  public RootResponse addRecordsItem(RecordsEntryItem recordsItem) {
    this.records.add(recordsItem);
    return this;
  }

   /**
   * Get records
   * @return records
  **/
  public List<RecordsEntryItem> getRecords() {
    return records;
  }

  public void setRecords(List<RecordsEntryItem> records) {
    this.records = records;
  }

  public RootResponse done(Boolean done) {
    this.done = done;
    return this;
  }

   /**
   * Get done
   * @return done
  **/
  public Boolean isDone() {
    return done;
  }

  public void setDone(Boolean done) {
    this.done = done;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootResponse RootResponse = (RootResponse) o;
    return Objects.equals(this.totalSize, RootResponse.totalSize) &&
        Objects.equals(this.records, RootResponse.records) &&
        Objects.equals(this.done, RootResponse.done);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalSize, records, done);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootResponse {\n");
    
    sb.append("    totalSize: ").append(toIndentedString(totalSize)).append("\n");
    sb.append("    records: ").append(toIndentedString(records)).append("\n");
    sb.append("    done: ").append(toIndentedString(done)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
