/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.salesvision.salesvision;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Rewards generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`REWARDS`")
public class Rewards implements Serializable {

    private Integer id;
    private Integer repid;
    private Integer monthlyCommission;
    private Integer quarterlyBonus;
    private Reps reps;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`REPID`", nullable = true, scale = 0, precision = 10)
    public Integer getRepid() {
        return this.repid;
    }

    public void setRepid(Integer repid) {
        this.repid = repid;
    }

    @Column(name = "`MONTHLY_COMMISSION`", nullable = true, scale = 0, precision = 10)
    public Integer getMonthlyCommission() {
        return this.monthlyCommission;
    }

    public void setMonthlyCommission(Integer monthlyCommission) {
        this.monthlyCommission = monthlyCommission;
    }

    @Column(name = "`QUARTERLY_BONUS`", nullable = true, scale = 0, precision = 10)
    public Integer getQuarterlyBonus() {
        return this.quarterlyBonus;
    }

    public void setQuarterlyBonus(Integer quarterlyBonus) {
        this.quarterlyBonus = quarterlyBonus;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`REPID`", referencedColumnName = "`ID`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_REWARDS_TO_REPS_REPID_ID`"))
    @Fetch(FetchMode.JOIN)
    public Reps getReps() {
        return this.reps;
    }

    public void setReps(Reps reps) {
        if(reps != null) {
            this.repid = reps.getId();
        }

        this.reps = reps;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Rewards)) return false;
        final Rewards rewards = (Rewards) o;
        return Objects.equals(getId(), rewards.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}
