/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.salesvision.salesvision;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Tasks generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TASKS`")
public class Tasks implements Serializable {

    private Integer id;
    private Date duedate;
    private Boolean done = false;
    private Integer repId;
    private Integer taskPriorityRef;
    private String description;
    private Reps reps;
    private TaskPriority taskPriority;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`DUEDATE`", nullable = true)
    public Date getDuedate() {
        return this.duedate;
    }

    public void setDuedate(Date duedate) {
        this.duedate = duedate;
    }

    @Column(name = "`DONE`", nullable = true)
    public Boolean getDone() {
        return this.done;
    }

    public void setDone(Boolean done) {
        this.done = done;
    }

    @Column(name = "`REP_ID`", nullable = true, scale = 0, precision = 10)
    public Integer getRepId() {
        return this.repId;
    }

    public void setRepId(Integer repId) {
        this.repId = repId;
    }

    @Column(name = "`TASK_PRIORITY_REF`", nullable = true, scale = 0, precision = 10)
    public Integer getTaskPriorityRef() {
        return this.taskPriorityRef;
    }

    public void setTaskPriorityRef(Integer taskPriorityRef) {
        this.taskPriorityRef = taskPriorityRef;
    }

    @Column(name = "`DESCRIPTION`", nullable = true, length = 655)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`REP_ID`", referencedColumnName = "`ID`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_BYCIJAABMA9A2AEHPR4RV9PMY`"))
    @Fetch(FetchMode.JOIN)
    public Reps getReps() {
        return this.reps;
    }

    public void setReps(Reps reps) {
        if(reps != null) {
            this.repId = reps.getId();
        }

        this.reps = reps;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`TASK_PRIORITY_REF`", referencedColumnName = "`ID`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_TASKS_TO_TASK_PRIORITF9xh6`"))
    @Fetch(FetchMode.JOIN)
    public TaskPriority getTaskPriority() {
        return this.taskPriority;
    }

    public void setTaskPriority(TaskPriority taskPriority) {
        if(taskPriority != null) {
            this.taskPriorityRef = taskPriority.getId();
        }

        this.taskPriority = taskPriority;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Tasks)) return false;
        final Tasks tasks = (Tasks) o;
        return Objects.equals(getId(), tasks.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}
