/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.salesvision.salesvision.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetRepsCountResponse implements Serializable {


    @ColumnAlias("count(*)")
    private Long count___;

    public Long getCount___() {
        return this.count___;
    }

    public void setCount___(Long count___) {
        this.count___ = count___;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetRepsCountResponse)) return false;
        final GetRepsCountResponse getRepsCountResponse = (GetRepsCountResponse) o;
        return Objects.equals(getCount___(), getRepsCountResponse.getCount___());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCount___());
    }
}
