/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.salesvision.salesforce.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * RootResponse
 */

public class RootResponse {
  @JsonProperty("access_token")
  private String access_token = null;

  @JsonProperty("signature")
  private String signature = null;

  @JsonProperty("instance_url")
  private String instance_url = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("token_type")
  private String token_type = null;

  @JsonProperty("issued_at")
  private String issued_at = null;

  public RootResponse access_token(String access_token) {
    this.access_token = access_token;
    return this;
  }

   /**
   * Get access_token
   * @return access_token
  **/
  public String getAccessToken() {
    return access_token;
  }

  public void setAccessToken(String access_token) {
    this.access_token = access_token;
  }

  public RootResponse signature(String signature) {
    this.signature = signature;
    return this;
  }

   /**
   * Get signature
   * @return signature
  **/
  public String getSignature() {
    return signature;
  }

  public void setSignature(String signature) {
    this.signature = signature;
  }

  public RootResponse instance_url(String instance_url) {
    this.instance_url = instance_url;
    return this;
  }

   /**
   * Get instance_url
   * @return instance_url
  **/
  public String getInstanceUrl() {
    return instance_url;
  }

  public void setInstanceUrl(String instance_url) {
    this.instance_url = instance_url;
  }

  public RootResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RootResponse token_type(String token_type) {
    this.token_type = token_type;
    return this;
  }

   /**
   * Get token_type
   * @return token_type
  **/
  public String getTokenType() {
    return token_type;
  }

  public void setTokenType(String token_type) {
    this.token_type = token_type;
  }

  public RootResponse issued_at(String issued_at) {
    this.issued_at = issued_at;
    return this;
  }

   /**
   * Get issued_at
   * @return issued_at
  **/
  public String getIssuedAt() {
    return issued_at;
  }

  public void setIssuedAt(String issued_at) {
    this.issued_at = issued_at;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootResponse RootResponse = (RootResponse) o;
    return Objects.equals(this.access_token, RootResponse.access_token) &&
        Objects.equals(this.signature, RootResponse.signature) &&
        Objects.equals(this.instance_url, RootResponse.instance_url) &&
        Objects.equals(this.id, RootResponse.id) &&
        Objects.equals(this.token_type, RootResponse.token_type) &&
        Objects.equals(this.issued_at, RootResponse.issued_at);
  }

  @Override
  public int hashCode() {
    return Objects.hash(access_token, signature, instance_url, id, token_type, issued_at);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootResponse {\n");
    
    sb.append("    access_token: ").append(toIndentedString(access_token)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    instance_url: ").append(toIndentedString(instance_url)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    token_type: ").append(toIndentedString(token_type)).append("\n");
    sb.append("    issued_at: ").append(toIndentedString(issued_at)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
