/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.salesvision.salesvision.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.salesvision.salesvision.models.query.*;

public interface SalesVisionQueryExecutorService {

    Page<GetDealStatusResponse> executeGetDealStatus(String reportingHead, String fromDate, String toDate, Pageable pageable);

    void exportGetDealStatus(String reportingHead, String fromDate, String toDate, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<GetExistingCustomersResponse> executeGetExistingCustomers(String repid, Pageable pageable);

    void exportGetExistingCustomers(String repid, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Integer executeUpdateQuoteStatusConverted(UpdateQuoteStatusConvertedRequest updateQuoteStatusConvertedRequest);

    Page<GetRepsCountResponse> executeGetRepsCount(String head, Pageable pageable);

    void exportGetRepsCount(String head, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    GetSalesSumResponse executeGetSalesSum(String fromDate, String toDate, String reportingHead, String repId);

    Page<GetTopPerformersResponse> executeGetTopPerformers(String target, String reportingHeadId, String fromDate, String toDate, Pageable pageable);

    void exportGetTopPerformers(String target, String reportingHeadId, String fromDate, String toDate, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<GetTopSellingSalesResponse> executeGetTopSellingSales(Pageable pageable);

    void exportGetTopSellingSales(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

}
