/*Copyright (c) 2019-2020 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.salesvision.convertquotestosales.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.bind.annotation.RestController;

import com.salesvision.convertquotestosales.ConvertQuotesToSales;
import com.salesvision.salesvision.Quotes;
import com.salesvision.salesvision.Sales;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;

/**
 * Controller object for domain model class {@link ConvertQuotesToSales}.
 * @see ConvertQuotesToSales
 */
@RestController
@Api(value = "ConvertQuotesToSalesController", description = "controller class for java service execution")
@RequestMapping("/convertQuotesToSales")
public class ConvertQuotesToSalesController {

    @Autowired
    private ConvertQuotesToSales convertQuotesToSales;

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @RequestMapping(value = "/convert", method = RequestMethod.POST, consumes = "multipart/form-data")
    public void convert(@RequestPart("quote") Quotes quote, @RequestPart("sale") Sales sale) {
        convertQuotesToSales.convert(quote, sale);
    }

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @RequestMapping(value = "/message", method = RequestMethod.GET)
    public String message(@RequestParam(value = "str", required = false) String str) {
        return convertQuotesToSales.message(str);
    }
}
